@startuml Boundary Diagram
!include <C4/C4_Container>

Person(student, "Student", "Recieves feedback and learns public speaking through the platform")
Person(admin, "Trainer", "Analises the stability results, manages users, and provides in person feedback")


System_Boundary(pivot, "PIVOT Software") { 
    Container(frontend, "Fronted application", "TBD", "Show visualization, user profiles and data")
    Container(backend, "Server application", "Django", "Data processing business logic")
    ContainerDb(db, "Relational DB", "PostgresSQL", "Store user data, session results")
    ContainerDb(obj, "Object Storage", "MiniIO", "Store raw files")
    ContainerDb(tims, "Time Series DB", "TBD", "Store the analyis and sensory data over time")
}

System_Ext(voice, "Voice analysis")
System_Ext(platform, "Pivot board", "Embbeded software")

Rel(student, frontend, "Uses")
Rel(admin, frontend, "Uses")

Rel(frontend, backend, "Requests data & Actions", "HTTPS")
Rel(backend, db, "Reads and writes", "HTTP")
Rel(backend, obj, "Reads and writes", "HTTP")
Rel(backend, tims, "Reads and writes", "HTTP")


Rel(backend, voice, "Sends raw data for voice analysis", "HTTPS")
Rel(platform, backend, "Sends data to the server", "WIFI?")

SHOW_LEGEND()
@enduml